name: Integration and deploy.
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ssh connection.
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "${{secrets.SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts
      - name: Clone sources.
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} <<EOF
            cd ~/src
            rm -rf ${{github.repository}}
            git clone ssh://git@github.com/${{github.repository}}.git
          EOF
      - name: Migrate up.
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} <<EOF
            cd ~/src/${{ github.event.repository.name }}
            docker run --rm \
              --network=skvdmt \
              --name migration \
              -v "/home/dima/src/${{ github.event.repository.name }}/schema:/migrations" \
              migrate/migrate:latest \
                -path /migrations \
                -database 'postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}?sslmode=disable' \
                up
          EOF
      - name: Testing.
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} <<EOF
            cd ~/src/${{ github.event.repository.name }}
            docker buildx build \
              --network=host \
              --target=testing \
              --output=type=docker \
              --build-arg MODE \
              --no-cache \
              --tag ${{github.repository}}:testing .
            docker rmi ${{github.repository}}:testing
          EOF
      - name: Building.
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} <<EOF
            cd ~/src/${{ github.event.repository.name }}
            docker build \
             --no-cache \
             --tag ${{github.repository}} .
          EOF
      - name: Remove sources.
        if: success() || failure()
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} <<EOF
            rm -rf ~/src/${{ github.event.repository.name }}
          EOF
      - name: Remove ssh connection.
        if: success() || failure()
        run: |
          rm -f ~/.ssh/id_rsa
          rm -f ~/.ssh/known_hosts
  deploy:
    needs: [integration]
    runs-on: ubuntu-latest
    steps:
      - name: Setup ssh connection.
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "${{secrets.SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts
      - name: Start app
        run: |
          ssh -i ~/.ssh/id_rsa ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} <<EOF
            docker stop ${{ github.event.repository.name }} || true
            docker rm ${{ github.event.repository.name }} || true
            docker run -d \
              --network=skvdmt \
              --name ${{ github.event.repository.name }} \
              --restart unless-stopped \
              --publish 8000:8000 \
              ${{github.repository}}
          EOF
      - name: Remove ssh connection.
        if: success() || failure()
        run: |
          rm -f ~/.ssh/id_rsa
          rm -f ~/.ssh/known_hosts
